export type propsTypeDataUser = {
  avenue: string
  classeActuelle: string
  commune: string
  created_at: string
  dateNaissance: string
  degreParente: string
  ecoleProvenance: string
  email: string
  id: number
  lieuNaissance: string
  maladie: string
  motdepasse: string
  nationalite: string
  nom: string
  nomMere: string
  nomPere: string
  optionEleve: string
  photo_path: string
  postNom: string
  pourcentage: number
  precisionSante: string
  prenom: string
  professionMere: string
  professionPere: string
  quartier: string
  religion: string
  sexe: string
  telephone: string
  updated_at: string
  creaded_at: string
}
