export { default as AnnouncementsView } from './Annonce'
export { Cours } from './Cours'
export { Horaires } from './Horraire'
export { default as ChatAI } from './NoteAIPage'
export { default as QuizPage } from './QuizPage'
