const STAFF = [
  {
    id: 1,
    name: 'Mme. Amina Kabila',
    role: 'Directrice',
    department: 'Direction',
    email: 'amina.kabila@ecole.ex',
    bio: 'Directrice passionnée par l’éducation inclusive.',
    img: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: 2,
    name: 'M. Didier Kambamba',
    role: 'Secrétaire',
    department: 'Direction',
    email: 'jean.b@ecole.ex',
    bio: 'Coordinateur pédagogique et ancien professeur de maths.',
    img: 'https://i.pravatar.cc/150?img=5',
  },
  {
    id: 3,
    name: 'Mme. Leonard',
    role: 'Préfet',
    department: 'Administration',
    email: 'solange.mbala@ecole.ex',
    bio: 'Responsable des inscriptions et des dossiers parentaux.',
    img: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: 4,
    name: 'M. Kitambala Hervé',
    role: 'Professeur de Math',
    department: 'Enseignants',
    email: 'olivier.k@ecole.ex',
    bio: 'Enseignante avec 8 ans d’expérience en cycles secondaires.',
    img: 'https://i.pravatar.cc/150?img=7',
  },
  {
    id: 5,
    name: 'M. Fabrice Ngonga.',
    role: 'Professeur en section Commerciale',
    department: 'Enseignants',
    email: 'claire.n@ecole.ex',
    bio: 'Enseignante avec 8 ans d’expérience en cycles secondaires.',
    img: 'https://i.pravatar.cc/150?img=16',
  },
  {
    id: 6,
    name: 'M. Kingi Chrispin',
    role: 'Professeur de Français',
    department: 'Enseignants',
    email: 'pierre.l@ecole.ex',
    bio: 'Passionné par la littérature francophone.',
    img: 'https://i.pravatar.cc/150?img=14',
  },
  {
    id: 7,
    name: 'Mme. Silvi Zola',
    role: "Professeur d'Anglais",
    department: 'Enseignants',
    email: 'rita.s@ecole.ex',
    bio: 'Passionné par la littérature Anglophone.',
    img: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 8,
    name: 'M. Kamenga',
    role: 'Directeur de Discipline',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. Trésor',
    role: 'D D adjoint',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. Blaise Kakobula',
    role: 'Professeur en section Commercialet',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Enseignante avec 8 ans d’expérience en cycles secondaires.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M.Tridon',
    role: 'Surveillant',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. Jean-Claude Kikanda',
    role: 'professeur de français',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
]

export default STAFF
