export { default as LandingPage } from './LandingPage'
export { default as AnnouncementPage } from './AnnouncementPage'
export { default as SchoolGalleryPage } from './SchoolGalleryPage'
export { default as OfflineStatus } from './OffLineStatus'
export { default as NotFindPage } from './NotFindPage'
