const ListeParClasse = [
  {
    name: 'Ecole primaire',
    classe: '1 ère Primaire',
    fillierCode: '1er',
    icon: '📚',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Ecole primaire',
    classe: '2 ème Primaire',
    fillierCode: '2eme',
    icon: '📚',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Ecole primaire',
    classe: '3 ème primaire',
    fillierCode: '3eme',
    icon: '📚',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Ecole primaire',
    classe: '4 ème',
    fillierCode: '4eme',
    icon: '📚',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Ecole primaire',
    classe: '5 ème',
    fillierCode: '5eme',
    icon: '📚',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Ecole primaire',
    classe: '6ème',
    fillierCode: '6eme',
    icon: '📚',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'Ecole Secondaire',
    classe: '7 ème',
    fillierCode: '7eme',
    icon: '🎓',
    color: 'from-indigo-500 to-purple-500',
  },
  {
    name: 'Ecole Secondaire',
    classe: '8 ème',
    fillierCode: '8eme',
    icon: '🎓',
    color: 'from-indigo-500 to-purple-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '1 ère Commerciale',
    fillierCode: '1 Commerciale',
    icon: '💼',
    color: 'from-green-500 to-emerald-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '2 ème Commercial',
    fillierCode: '2 Commercial',
    icon: '💼',
    color: 'from-green-500 to-emerald-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '3 ème Commercial',
    fillierCode: '3 Commercial',
    icon: '💼',
    color: 'from-green-500 to-emerald-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '4 ème Commercial',
    fillierCode: '4 Commercial',
    icon: '💼',
    color: 'from-green-500 to-emerald-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '1 ère Coupe et Couture',
    fillierCode: '1 Coupe et Couture ',
    icon: '✂️',
    color: 'from-orange-500 to-amber-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '2 ème Coupe et Couture',
    fillierCode: '2 Coupe et Couture',
    icon: '✂️',
    color: 'from-orange-500 to-amber-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '3 ème Coupe et Couture',
    fillierCode: '3 Coupe et Couture',
    icon: '✂️',
    color: 'from-orange-500 to-amber-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '4 ème Coupe et Couture',
    fillierCode: '4 Coupe et Couture',
    icon: '✂️',
    color: 'from-orange-500 to-amber-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '1 ère Littéraire',
    fillierCode: '1 Littéraire',
    icon: '📖',
    color: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '2 ème Littéraire',
    fillierCode: '2 Littéraire',
    icon: '📖',
    color: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '3 ème Littéraire',
    fillierCode: '3 Littéraire',
    icon: '📖',
    color: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '4 ème Littéraire',
    fillierCode: '4 Littéraire',
    icon: '📖',
    color: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '1 ère Pédagogique',
    fillierCode: '1 Pédagogique',
    icon: '👨‍🏫',
    color: 'from-teal-500 to-cyan-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '2 ème Pédagogique',
    fillierCode: '2 Pédagogique',
    icon: '👨‍🏫',
    color: 'from-teal-500 to-cyan-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '3 ème Pédagogique',
    fillierCode: '3 Pédagogique',
    icon: '👨‍🏫',
    color: 'from-teal-500 to-cyan-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '4 ème Pédagogique',
    fillierCode: '4 Pédagogique',
    icon: '👨‍🏫',
    color: 'from-teal-500 to-cyan-500',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '1 ère Scientifique',
    fillierCode: '1 Scientifique',
    icon: '🔬',
    color: 'from-blue-600 to-indigo-600',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '2 ème Scientifique',
    fillierCode: '2 Scientifique',
    icon: '🔬',
    color: 'from-blue-600 to-indigo-600',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '3 ème Scientifique',
    fillierCode: '3 Scientifique',
    icon: '🔬',
    color: 'from-blue-600 to-indigo-600',
  },
  {
    name: 'Ecole Humanitaire',
    classe: '4 ème Scientifique',
    fillierCode: '4 Scientifique',
    icon: '🔬',
    color: 'from-blue-600 to-indigo-600',
  },
]

export default ListeParClasse
