const STAFF = [
  {
    id: 1,
    name: 'Mme. Amina Kabila',
    role: 'Directrice',
    department: 'Direction',
    email: 'amina.kabila@ecole.ex',
    bio: 'Directrice passionnée par l’éducation inclusive.',
    img: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: 2,
    name: 'M. Didier Kambamba',
    role: 'Secrétaire',
    department: 'Direction',
    email: 'jean.b@ecole.ex',
    bio: 'Coordinateur pédagogique et professeur de comptabilité.',
    img: '/assets/prof_didier2.jpg',
  },
  {
    id: 3,
    name: 'M. Leonard Mbungi ',
    role: 'Préfet',
    department: 'Direction',
    email: 'solange.mbala@ecole.ex',
    bio: 'Responsable des inscriptions et des dossiers parentaux.',
    img: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: 3,
    name: "M. L'Abbé Henock",
    role: 'Promoteur',
    department: 'administarctions',
    email: 'solange.mbala@ecole.ex',
    bio: "Responsable de l'école ",
    img: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: 4,
    name: 'M. Kitambala Hervé',
    role: 'Professeur de Math',
    department: 'Enseignants',
    email: 'olivier.k@ecole.ex',
    bio: 'Professeur passionné par la résolution de problèmes et l’enseignement des mathématiques.',
    img: '/assets/prof_hervé.jpg',
  },
  {
    id: 5,
    name: 'M. Fabrice Ngonga.',
    role: 'Professeur en section Commerciale',
    department: 'Enseignants',
    email: 'claire.n@ecole.ex',
    bio: 'Spécialiste en stratégie commerciale et gestion d’entreprise, engagé pour la réussite de ses élèves.',
    img: '/assets/prof_fabrice.jpg',
  },
  {
    id: 6,
    name: 'M. Kingi Chrispin',
    role: 'Professeur de Français',
    department: 'Enseignants',
    email: 'pierre.l@ecole.ex',
    bio: 'Professeur motivé par la transmission de la culture et de la langue française.',
    img: 'https://i.pravatar.cc/150?img=14',
  },
  {
    id: 7,
    name: 'Mme. Silvi Zola',
    role: "Professeur d'Anglais",
    department: 'Enseignants',
    email: 'rita.s@ecole.ex',
    bio: 'Professeur motivé par la transmission de la culture et de la langue anglaise.',
    img: '/assets/sylvie_zola.jpg',
  },
  {
    id: 8,
    name: 'M. Kamenga',
    role: 'Directeur de Discipline',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: '/assets/dd_kamenga.jpg',
  },
  {
    id: 8,
    name: 'M. Trésor',
    role: 'D D adjoint',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. Blaise Kakobula',
    role: 'Professeur en section Commercialet',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'passionné gestion commerciale, dédié à l’apprentissage et au succès des étudiants.',
    img: '/assets/prof_blaise.jpg',
  },
  {
    id: 8,
    name: 'M.Tridon Yangongo',
    role: 'Surveillant',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Professeur dévoué à la réussite et à l’éveil scientifique des étudiants.',
    img: '/assets/tridon.jpg',
  },
  {
    id: 8,
    name: 'M. Jean-Claude Kikanda',
    role: 'professeur de français',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Professeur passionné par la langue française et la littérature francophone.',
    img: '/assets/prof_kikanda.jpg',
  },
  {
    id: 8,
    name: 'M. Idéal Mvumbu',
    role: 'professeur de math',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Professeur motivé par la transmission des connaissances et la réussite scolaire en mathématiques.',
    img: '/assets/prof_van.jpg',
  },
  {
    id: 8,
    name: 'M. Hyrson Rosaire',
    role: 'Surveillant',
    department: 'Enseignants',
    email: 'andre.m@ecole.ex',
    bio: 'Pédagogue expérimenté, passionné par la transmission des connaissances scientifiques.',
    img: '/assets/prof_rosaire.jpg',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 8,
    name: 'M. André M.',
    role: 'Surveillant',
    department: 'Technique & Logistique',
    email: 'andre.m@ecole.ex',
    bio: 'Surveillance, encadrement et gestion des pauses.',
    img: 'https://i.pravatar.cc/150?img=10',
  },
]

export default STAFF
